"""Optimization page — NSGA-II Pareto front and representative operating conditions."""

import streamlit as st
import plotly.graph_objects as go
import pandas as pd

from utils.styling import section_header, card_open, card_close, pill, style_table
from utils.data_loader import load_all_reference_data

STRATEGY_COLORS = {"High Production": "#DC2626", "Balanced": "#059669", "Conservative": "#2563EB"}
HOVERLABEL = dict(bgcolor="white", font_color="#0F172A", font_size=13, bordercolor="#E2E8F0")


def render(go_to):
    section_header(
        "Multi-Objective Optimization — NSGA-II",
        "Pareto-optimal operating conditions for the PEM electrolyser, generated by coupling the validated GPR surrogate with NSGA-II.",
    )

    data, errors = load_all_reference_data()
    pareto = data.get("pareto")
    op_conditions = data.get("operating_conditions")

    if pareto is None:
        st.error(f"Could not load Pareto results ({errors.get('pareto')}).")
        return

    # ---------------- KPI strip ----------------
    k1, k2, k3, k4 = st.columns(4)
    with k1:
        st.markdown(f"""<div class="kpi-card kpi-blue"><div class="kpi-label">Pareto Solutions</div>
        <div class="kpi-value">{len(pareto)}</div></div>""", unsafe_allow_html=True)
    with k2:
        st.markdown(f"""<div class="kpi-card kpi-green"><div class="kpi-label">Max H₂ Production</div>
        <div class="kpi-value" style="font-size:20px;">{pareto['H2'].max():.2e}</div><div class="kpi-unit">mol/s</div></div>""", unsafe_allow_html=True)
    with k3:
        st.markdown(f"""<div class="kpi-card kpi-orange"><div class="kpi-label">Min Voltage Loss</div>
        <div class="kpi-value">{pareto['Voltage Loss'].min():.3f}</div><div class="kpi-unit">V</div></div>""", unsafe_allow_html=True)
    with k4:
        st.markdown(f"""<div class="kpi-card kpi-purple"><div class="kpi-label">Min Degradation</div>
        <div class="kpi-value">{pareto['Degradation'].min():.3f}</div></div>""", unsafe_allow_html=True)

    st.write("")

    # ---------------- Pareto front ----------------
    section_header("Pareto Front", "Trade-off between Hydrogen Production and Voltage Loss across 200 non-dominated operating conditions.")

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=pareto["Voltage Loss"], y=pareto["H2"],
        mode="markers",
        marker=dict(size=8, color=pareto["Degradation"], colorscale="Blues", showscale=True,
                    colorbar=dict(title="Degradation"), line=dict(width=0.5, color="white")),
        name="Pareto Solutions",
        text=[f"T={t:.1f}K, V={v:.3f}V, σ={c:.2f}" for t, v, c in
              zip(pareto["Temperature"], pareto["Voltage"], pareto["Conductivity"])],
        hovertemplate="Voltage Loss: %{x:.3f}<br>H₂: %{y:.3e}<br>%{text}<extra></extra>",
    ))

    if op_conditions is not None:
        for _, row in op_conditions.iterrows():
            label = row.iloc[0]
            color = STRATEGY_COLORS.get(label, "#0F172A")
            fig.add_trace(go.Scatter(
                x=[row["Voltage Loss"]], y=[row["H2"]],
                mode="markers", marker=dict(size=16, color=color, symbol="star", line=dict(width=1, color="white")),
                name=str(label),
                hovertemplate=f"<b>{label}</b><br>Voltage Loss: %{{x:.3f}}<br>H₂: %{{y:.3e}}<extra></extra>",
            ))

    fig.update_layout(
        height=460, margin=dict(l=10, r=10, t=10, b=10),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        xaxis_title="Voltage Loss (V)", yaxis_title="Hydrogen Production (mol/s)",
        legend=dict(orientation="h", y=-0.2),
        font=dict(color="#0F172A"),
        hoverlabel=HOVERLABEL,
    )
    card_open()
    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})
    card_close()

    st.write("")

    # ---------------- Additional interactive views ----------------
    section_header("Objective Space Explorer")
    obj_options = ["H2", "Efficiency", "Voltage Loss", "Degradation"]
    c1, c2 = st.columns(2)
    with c1:
        x_axis = st.selectbox("X axis", obj_options, index=2)
    with c2:
        y_axis = st.selectbox("Y axis", obj_options, index=1)

    fig2 = go.Figure(go.Scatter(
        x=pareto[x_axis], y=pareto[y_axis], mode="markers",
        marker=dict(size=8, color=pareto["Temperature"], colorscale="Turbo", showscale=True,
                    colorbar=dict(title="Temperature (K)")),
    ))
    fig2.update_layout(
        height=400, margin=dict(l=10, r=10, t=10, b=10),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        xaxis_title=x_axis, yaxis_title=y_axis, font=dict(color="#0F172A"),
        hoverlabel=HOVERLABEL,
    )
    card_open()
    st.plotly_chart(fig2, use_container_width=True, config={"displayModeBar": False})
    card_close()

    st.write("")

    # ---------------- Recommended operating conditions ----------------
    section_header("Recommended Operating Conditions", "Representative points selected via ideal-point distance from the Pareto front.")
    if op_conditions is not None:
        display_df = op_conditions.copy()
        display_df.rename(columns={display_df.columns[0]: "Strategy"}, inplace=True)
        st.dataframe(
            style_table(display_df.style.format({
                "Temperature": "{:.2f}", "Voltage": "{:.3f}", "Conductivity": "{:.2f}",
                "H2": "{:.3e}", "Efficiency": "{:.4f}", "Voltage Loss": "{:.4f}", "Degradation": "{:.4f}",
            })),
            use_container_width=True, hide_index=True,
        )

        rec_cols = st.columns(3)
        recs = {
            "High Production": "Prioritises maximum hydrogen generation, accepting higher voltage loss and faster degradation — suited to short campaigns or peak-demand operation.",
            "Balanced": "Best overall compromise across all four objectives — recommended as the default continuous operating point.",
            "Conservative": "Minimises degradation and voltage loss at the cost of lower hydrogen output — recommended for maximising membrane lifetime.",
        }
        for c, (name, text) in zip(rec_cols, recs.items()):
            with c:
                color = STRATEGY_COLORS.get(name, "#0F172A")
                st.markdown(
                    f"""<div class="card">
                    <div style="font-weight:700;color:{color};margin-bottom:6px;">{name}</div>
                    <div style="font-size:13px;color:#475569;line-height:1.5;">{text}</div>
                    </div>""",
                    unsafe_allow_html=True,
                )
    else:
        st.warning(f"Recommended operating conditions unavailable ({errors.get('operating_conditions')}).")

    st.write("")

    # ---------------- Downloads ----------------
    d1, d2 = st.columns(2)
    with d1:
        st.download_button(
            "⬇️ Download Pareto Front (CSV)",
            data=pareto.to_csv(index=False),
            file_name="pareto_front.csv", mime="text/csv", use_container_width=True,
        )
    with d2:
        if op_conditions is not None:
            st.download_button(
                "⬇️ Download Optimal Operating Points (CSV)",
                data=op_conditions.to_csv(index=False),
                file_name="optimal_operating_conditions.csv", mime="text/csv", use_container_width=True,
            )
